### ISSUE TITLE
How do i remove the [0] before the prompt?

### ISSUE THREAD

**Issue by condense-fidelity-elope** [dosentmatter/rainbow-bash-prompt#2]
I can't figure out how to

**Comment by dosentmatter** [comment]
Deleting [these lines](https://github.com/dosentmatter/rainbow-bash-prompt/blob/3fb58fc635a0a48943e3a602f98bc48ee7607e15/.bash_prompt#L81-L91) should remove it.

Closing the issue. You can reopen if the above solution doesn't work.
